# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('iterations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('estimate_time', models.FloatField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iterations.Iteration')),
            ],
        ),
    ]
